# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  somewebappui:
    image: somewebappui
    build:
      context: .
      dockerfile: SomeWebApp.UI/Dockerfile
    ports:
      - 5044:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_SERVICE_FQDN=somewebappapi:8080
    depends_on:
      - somewebappapi
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  somewebappapi:
    image: somewebappapi
    build:
      context: .
      dockerfile: SomeWebApp.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
