# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: somewebapp
services:
- name: jaeger
  image: jaegertracing/all-in-one
  bindings:
    - name: ui
      protocol: http
      port: 16686
      containerPort: 16686
    - name: collector-endpoint
      protocol: http
      port: 14268
      containerPort: 14268
    - name: collector-endpoint-proto
      protocol: http
      port: 14250
      containerPort: 14250
    - name: agent-over-compact-thrift-protocol
      protocol: udp
      port: 6831
      containerPort: 6831
    # - name: agent-over-binary-thrift-protocol
    #   protocol: udp
    #   port: 6832
    #   containerPort: 6832
- name: otel
  image: otel/opentelemetry-collector:0.48.0
  args: --config=/etc/otel-collector-config.yaml
  bindings:
    - name: grpc-receiver
      port: 4317
      containerPort: 4317
  volumes:
    - source: ./otel-collector-config.yaml
      target: /etc/otel-collector-config.yaml
    - source: ./output
      target: /etc/output
- name: ui
  project: SomeWebApp.UI/SomeWebApp.UI.csproj
  bindings:
    - port: 5001
      protocol: https
      name: https
    - port: 5000
      protocol: http
      name: http
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: API_SERVICE_FQDN
    value: localhost:6001
- name: api
  project: SomeWebApp.API/SomeWebApp.API.csproj
  bindings:
    - port: 6001
      protocol: https
      name: https
    - port: 6000
      protocol: http
      name: http
